stages:
  clean_data:
    cmd: python src/load_clean.py data/iris.csv data/cleaned.csv
    deps:
    - data/iris.csv
    - src/load_clean.py
    outs:
    - data/cleaned.csv
  train_model:
    cmd: python src/train.py data/cleaned.csv models/model.pkl metrics.json
    deps:
    - data/cleaned.csv
    - src/train.py
    outs:
    - models/model.pkl
    metrics:
    - metrics.json:
        cache: false
  load_to_postgres:
    cmd: python src/load_to_db.py data/cleaned.csv
    deps:
    - data/cleaned.csv
    - src/load_to_db.py
